### ISSUE TITLE
package missing in setup.py

### ISSUE THREAD

**Issue by xtyangpsp** [nfsi-canada/OBStools#20]
Thanks for sharing this great package. I found that to successfully install the package, you should added in the setup.py file:
`packages=['obstools','obstools.atacr']`.

Otherwise, the scripts under obstools.atacr cannot be found.

This is an easy fix.

Xiaotao Yang

**Comment by paudetseis** [comment]
Thank you for your edits. I have never had a problem importing the atacr modules before, so this sounds a little bit strange to me. Thank you for pointing this out and I will test it further.

**Comment by paudetseis** [comment]
I just merged your pull request to master. After pulling locally from the remote master, I un-installed the package, removed `'OBStools.atacr'` in the `packages` definition, then re-installed the package successfully. I then opened a Python window and tested importing the `atacr` module. There was no error produced, see below:

```
(obs) Pascals-MacBook-Pro:OBStools pascalaudet$ python
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:05:27) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import obstools.atacr
>>> from obstools import atacr
>>> from obstools.atacr import DayNoise
>>> import obstools.atacr.utils
```

If you can please reproduce your error in importing the `atacr` package, please post it here.
